import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [error, setError] = useState("")
  const [message, setMessage] = useState("")
  const [file, setFile] = useState<File | null>(null)

  const onFileChange = (event : Event) => {
    if (event.target === null){
      return;
    }
    //@ts-ignore
    let file: File = (event.target as HTMLInputElement).files[0];
    setFile(file);
   }

   const uploadFile = (event: Event) => {
    if (event.target === null){
      return;
    }
        
    //@ts-ignore
    const target : HTMLInputElement = event.target;
    setError('')
    setMessage('');
    // send data

    // let data = new FormData();
    // data.append('file', file);
    // data.append('name', file.name);
    // fetch('http://localhost:8080/api/files', {
    // method: 'POST',
    // body: data
    // }).then(response => {
    // setError('')
    // setMessage('Sucessfully uploaded file');
    // }).catch(err => {
    // setError(err);
    // });
   }

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main>
      <div>
 <h2>Upload a file</h2>
 <h4 style={{color: 'red'}}>{error}</h4>
 <h4 style={{color: 'green'}}>{message}</h4>
 <input onChange={onFileChange} type="file"></input>
 <button onClick={uploadFile}>Upload</button>
</div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
